

export const NavigationStateActions = {
    GO_TO_MAP: "GO_TO_MAP",
    GO_TO_LOCATIONS: "GO_TO_LOCATIONS"
};

export const LocationsStateActions = {
    ADD_NEW_LOCATION: "ADD_NEW_LOCATION",
    REMOVE_LOCATION: "REMOVE_LOCATION",
    UPDATE_LOCATION: "UPDATE_LOCATION",
    SET_DEVICE_LAST_LOCATION: "SET_DEVICE_LAST_LOCATION",
    SHOW_MARKER_DETAIL_VIEW: "SHOW_MARKER_DETAIL_VIEW",
    HIDE_MARKER_DETAIL_VIEW: "HIDE_MARKER_DETAIL_VIEW"
};